version: '3.8'

services:
  product-apis:
    build:
      context: ./product-apis
      dockerfile: Dockerfile
    container_name: product-apis
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: master
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - '3000:3000'
    volumes:
      - ./product-apis:/app
      - /app/node_modules
    command: ['npm', 'run', 'start']

  order-apis:
    build:
      context: ./order-apis
      dockerfile: Dockerfile
    container_name: order-apis
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: master
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - '3001:3001'
    volumes:
      - ./order-apis:/app
      - /app/node_modules
    command: ['npm', 'run', 'start']

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: master
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    driver: local
